name: build
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo lambda
        run: |
          python -m pip install --upgrade pip
          pip install cargo-lambda
        shell: bash
      - name: Build lambda function
        run: |
          cd ${{ inputs.lambda_directory }}
          cargo lambda build --release --arm64
        shell: bash
