name: build
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Build Dependencies
        run: sudo apt-get update && sudo apt-get install pkg-config libssl-dev
      - name: Install cargo lambda
        run: |
          python -m pip install --upgrade pip
          pip install cargo-lambda
        shell: bash
      - name: Build lambda function
        run: OPENSSL_DIR=/usr/local/ssl cargo lambda build --release --arm64
        shell: bash
